FROM openjdk:11.0.15-jdk
WORKDIR /target/
ADD MiracleSolution-CLI-1.0-SNAPSHOT-jar-with-dependencies.jar MiracleSolution-CLI-1.0-SNAPSHOT-jar-with-dependencies.jar
EXPOSE 8080
CMD java -jar MiracleSolution-CLI-1.0-SNAPSHOT-jar-with-dependencies.jar
